<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>

        <IsPackable>false</IsPackable>
        <GenerateProgramFile>false</GenerateProgramFile>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FsUnit.xUnit" Version="7.1.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NodaTime" Version="3.2.3"/>
        <PackageReference Include="Shouldly" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Orders\LoanOrderAssert.fs"/>
        <Compile Include="Orders\LoanOrderServiceTests.fs"/>
        <Compile Include="Verifications\PeriodExtensions.fs"/>
        <Compile Include="Verifications\VerificationAssert.fs"/>
        <Compile Include="Verifications\AgeVerificationServiceTests.fs"/>
        <Compile Include="Program.fs" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\LoanService\LoanService.fsproj"/>
    </ItemGroup>

</Project>
